spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/auth/realms/hackathon-organizer/protocol/openid-connect/certs
  config:
    import: optional:configserver:http://localhost:8888/
    label: user-write-service
  cloud:
    vault:
      generic:
        enabled: true
        profile-separator: '/'
        default-context: user-write-service
  application:
    name: user-write-service
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
keycloak:
  authUrl: http://localhost:8080/auth
  realm: hackathon-organizer
  masterRealm: master
  clientId: admin-cli
  username: admin
  password: admin
server:
  port: 0